require 'webmock/rspec'
WebMock.disable_net_connect!(allow_localhost: true)

# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See https://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups

  config.before(:each) do
    json_return = {
      page: 1,
      results: [
        {
          adult: false,
          id: 716088,
          original_language: "en",
          original_title: "Sydney 2000 Olympics Opening Ceremony",
          overview: "Coverage of the glorious Olympic Opening Ceremony of the Games in Sydney.",
          release_date: "2000-09-15",
          title: "Sydney 2000 Olympics Opening Ceremony",
          vote_average: 7.3,
          vote_count: 3
        },
        {
          adult: false,
          id: 716098,
          original_language: "en",
          original_title: "Sydney 2000 Olympics Closing Ceremony",
          overview: "The 2000 Summer Olympics Closing Ceremony took place on 1 October 2000 in Stadium Australia.",
          release_date: "2000-10-01",
          title: "Sydney 2000 Olympics Closing Ceremony",
          vote_average: 10,
          vote_count: 1
        }
      ],
      total_pages: 1,
      total_results: 2
    }

    stub_request(:get, /api\.themoviedb\.org/).
      with(headers: { 'Accept' => '*/*' }).
      to_return(status: 200, body: JSON.generate(json_return), headers: {})
  end

=begin
  config.filter_run_when_matching :focus
  config.example_status_persistence_file_path = "spec/examples.txt"
  config.disable_monkey_patching!

  if config.files_to_run.one?
    config.default_formatter = "doc"
  end

  config.profile_examples = 10
  config.order = :random
  Kernel.srand config.seed
=end
end